### ISSUE TITLE
[Bug] Premium validation error in local dev environment

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-backup#183]
**Describe the bug**
Error produced in Backup Archives, Transfers, and Settings tabs when using a Total Upkeep Premium in a local environment created with Laragon.

`Fatal error: Uncaught GuzzleHttp\Ring\Exception\RingException: cURL error 77: error setting certificate verify locations: CAfile: L:\laragon\etc\ssl\cacert.pem CApath: none in C:\laragon\www\eco1\wp-content\plugins\boldgrid-backup-premium\vendor\guzzlehttp\ringphp\src\Client\CurlFactory.php:127`

Stack trace:
`#0 C:\laragon\www\eco1\wp-content\plugins\boldgrid-backup-premium\vendor\guzzlehttp\ringphp\src\Client\CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Array, Array, Array)`
`#1 C:\laragon\www\eco1\wp-content\plugins\boldgrid-backup-premium\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php(96): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Array, Array, Array, Array, Resource id #899)`
`#2 C:\laragon\www\eco1\wp-content\plugins\boldgrid-backup-premium\vendor\guzzlehttp\ringphp\src\Client\CurlHandler.php(68): GuzzleHttp\Ring\Client\CurlHandler->_invokeAsArray(Array)`
`#3 C:\laragon\www\eco1\wp-content\plugins\boldgrid-backup-premium\vendor\guzzlehttp\ringphp\src\Client\Middleware.php(54 in C:\laragon\www\eco1\wp-content\plugins\boldgrid-backup-premium\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 51`

**To Reproduce**
1. Create a local environment with Laragon and configure Total Upkeep Premium.
2. Select Backup Archives, Transfers, or Settings tabs.
3. See error

**Expected behavior**
Error should not be present and the plugin should work as expected.

**Comment by joe9663** [comment]
User resolved issue on their end, misconfiguration in their environment.
