### ISSUE TITLE
[Bug] Unable to restore backups on some GoDaddy accounts

### ISSUE THREAD

**Issue by joe9663** [BoldGrid/boldgrid-backup#184]
**Describe the bug**
Some GoDaddy accounts cannot restore backups, 500 error produced when trying to run the restoration.

```Fatal error: Uncaught Error: Class 'ZipArchive' not found in /home/user/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-restore-helper.php:242```
```Stack trace:```
```#0 /home/user/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-core.php(2180): Boldgrid_Backup_Admin_Restore_Helper->set_writable_permissions('/home/yneisrpij...')```
```#1 /home/user/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-core.php(2682): Boldgrid_Backup_Admin_Core->restore_archive_file()```
```#2 /home/user/public_html/wp-includes/class-wp-hook.php(288): Boldgrid_Backup_Admin_Core->wp_ajax_restore('')```
```#3 /home/user/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)```
```#4 /home/user/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)```
```#5 /home/user/public_html/wp-admin/admin-ajax.php(175): do_action('wp_ajax_boldgri...')```
```#6 {main} thrown in /home/user/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-restore-helper.php on line 242```

**Expected behavior**
If ZipArchive is not available on the server then Total Upkeep should at least report to users that the required functionality is not available to restore a backup.

**Comment by joe9663** [comment]
Enabling the zip extension in the server PHP version settings fixed the problem and restorations now run successfully.
