### ISSUE TITLE
Undefined index: plugins in admin/class-boldgrid-backup-admin-auto-updates.php

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#267]
```
[2020-05-18 12:15:55 UTC] PHP shutdown - Error found: Array
(
    [type] => 8
    [message] => Undefined index: plugins
    [file] => /home/bradm/public_html/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-auto-updates.php
    [line] => 120
)
```

**Comment by bwmarkle** [comment]
@jamesros161 - @cssjoe just reported this too.

**Comment by cssjoe** [comment]
I also got a fatal error:
```
[19-May-2020 14:53:08 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WP_Error::setUpdateData() in /home/joec/public_html/wp-content/plugins/boldgrid-backup-premium/admin/class-boldgrid-backup-premium-admin-plugins.php:63
Stack trace:
#0 /home/joec/public_html/wp-includes/class-wp-hook.php(287): Boldgrid_Backup_Premium_Admin_Plugins->print_update_message(Array, Object(stdClass))
#1 /home/joec/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/joec/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/joec/public_html/wp-admin/includes/update.php(562): do_action('in_plugin_updat...', Array, Object(stdClass))
#4 /home/joec/public_html/wp-includes/class-wp-hook.php(289): wp_plugin_update_row('weforms-pro/wef...', Array)
#5 /home/joec/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#6 /home/joec/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /home/joec/public_html/wp-admin/includes/class-wp-plugins-list-table.php(1012): do in /home/joec/public_html/wp-content/plugins/boldgrid-backup-premium/admin/class-boldgrid-backup-premium-admin-plugins.php on line 63
```
