### ISSUE TITLE
Class 'Boldgrid\Library\Library\Ui\Card' not found

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/boldgrid-backup#316]
```
Fatal error:
Uncaught Error: Class 'Boldgrid\Library\Library\Ui\Card' not found in /home/*********/*********/wp-content/plugins/boldgrid-backup/admin/card/class-amazon-s3.php:23

Stack trace:
#0 /home/*********/*********/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php(251): require_once() 
#1 /home/*********/*********/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php(70): Boldgrid_Backup->load_dependencies()
#2 /home/*********/*********/wp-content/plugins/boldgrid-backup/boldgrid-backup.php(81): Boldgrid_Backup->__construct() 
#3 /home/*********/*********/wp-content/plugins/boldgrid-backup/boldgrid-backup.php(147): run_boldgrid_backup()
#4 /home/*********/*********/wp-admin/includes/plugin.php(2255): include('/home/dh_ssksqt...')
#5 /home/*********/*********/wp-admin/plugins.php(177): plugin_sandbox_scrape('boldgrid-backup...')
#6 {main} thrown in /home/*********/*********/wp-content/plugins/boldgrid-backup/admin/card/class-amazon-s3.php on line 23

```

**Comment by bwmarkle** [comment]
The [library fix](https://github.com/BoldGrid/library/commit/542c9cc0b8d434112bfbf4ba8df7a00fe275b18f) will prevent a fatal here
![image](https://user-images.githubusercontent.com/5925563/85453323-be78c200-b569-11ea-957c-e3ce25dfe7fe.png)
