### ISSUE TITLE
Fatal Error "Call to undefined method Library\...\Plugins" on DreamHost PHP 7.4

### ISSUE THREAD

**Issue by jessecowens** [BoldGrid/boldgrid-backup#367]
**Describe the bug**
[DreamHost users running PHP 7.4](https://boldgrid.slack.com/archives/CJFR0K5MG/p1597274080002500) are encountering a fatal error after upgrading to WP 5.5:
```
[Wed Aug 12 11:54:06.372427 2020] [proxy_fcgi:error] [pid 14439] [client 154.160.14.37:53886] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method Boldgrid\\Library\\Library\\Plugin\\Plugins::getAllPlugins() in /home/wp_s3q2qj/betterthinking.co/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-auto-updates.php:64\nStack trace:\n#0 /home/wp_s3q2qj/betterthinking.co/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-core.php(737): Boldgrid_Backup_Admin_Auto_Updates->__construct()\n#1 /home/wp_s3q2qj/betterthinking.co/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php(338): Boldgrid_Backup_Admin_Core->__construct()\n#2 /home/wp_s3q2qj/betterthinking.co/wp-content/plugins/boldgrid-backup/includes/class-boldgrid-backup.php(72): Boldgrid_Backup->define_admin_hooks()\n#3 /home/wp_s3q2qj/betterthinking.co/wp-content/plugins/boldgrid-backup/boldgrid-backup.php(81): Boldgrid_Backup->__construct()\n#4 /home/wp_s3q2qj/betterthinking.co/wp-content/plugins/boldgrid-backup/boldgrid-backup.php(147): run_boldgrid_backup()\n#5 /home/wp_s3q2qj/b...
```

**Comment by bwmarkle** [comment]
I'm about to push up a "fix". It's going to show this instead:

![image](https://user-images.githubusercontent.com/5925563/90136084-9f183d00-dd41-11ea-83b2-e6c0e5dd3caa.png)
