### ISSUE TITLE
Creation of dynamic property phpseclib\Crypt\Rijndael::$name is deprecated

### ISSUE THREAD

**Issue by SitesByYogi** [BoldGrid/boldgrid-backup#575]
In response to this WordPress.org topic - [(https://wordpress.org/support/topic/ftp-backup-deprecated/)]
for TU with PHP warning Creation of dynamic property `phpseclib\Crypt\Rijndael::$name` is deprecated.
`vendor/phpseclib/phpseclib/phpseclib/Crypt/Rijndael.php`
`phpseclib/phpseclib`                2.0.39
The latest version is 3.0.34.
It appears that is fixed in 3.0.22 -- `Rijndael: fix E_DEPRECATED (#1935)`

Resolution:

Someone will have to update the `composer.json` file and run composer `update -o` and then test the plugin.

**Comment by W3ap0n-X** [comment]
User did receive most recent updates but is now experiencing additional difficulties only receiving critical errors when trying to navigate to Backups / Transfers / Settings tabs in the dashboard and receiving the following errors:
```
Fatal error: Uncaught Error: Class "phpseclib\Net\SFTP" not found in <root_dir>/wp-content/plugins/boldgrid-backup/admin/remote/class-boldgrid-backup-admin-ftp.php:298
Stack trace:
#0 <root_dir>/wp-content/plugins/boldgrid-backup/admin/remote/class-boldgrid-backup-admin-ftp.php(1141): Boldgrid_Backup_Admin_Ftp->connect()
#1 <root_dir>/wp-content/plugins/boldgrid-backup/admin/remote/class-boldgrid-backup-admin-ftp-hooks.php(216): Boldgrid_Backup_Admin_Ftp->upload('<root_dir>...')
#2 <root_dir>/wp-includes/class-wp-hook.php(324): Boldgrid_Backup_Admin_Ftp_Hooks->upload_post_archiving('/home/alineadmi...')
#3 <root_dir>/wp-includes/plugin.php(205): WP_Hook->apply_filters('<root_dir>...', Array)
#4 <root_dir>/wp-content/plugins/boldgrid-backup/admin/class-boldgrid-backup-admin-jobs.php(314): apply_filters('boldgrid_backup...', '<root_dir>...')
#5 <root_dir>/wp-includes/class-wp-hook.php(324): Boldgrid_Backup_Admin_Jobs->run()
#6 <root_dir>/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#7 <root_dir>/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#8 <root_dir>/wp-cron.php(191): do_action_ref_array('boldgrid_backup...', Array)
#9 {main}
thrown in <root_dir>/wp-content/plugins/boldgrid-backup/admin/remote/class-boldgrid-backup-admin-ftp.php on line 298
```
